
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: flightbooking_dev_db
    environment:
      POSTGRES_DB: flightdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: password
    depends_on:
      - db
    ports:
      - "5002:5002"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

volumes:
  db_data_dev:
